[Log]
Level = 'warn'

[WebServer]
AllowOrigins = '\*'
SecureCookies = false

[WebServer.TLS]
HTTPSPort = 0

[[EVM]]
ChainID = '421614'

[[EVM.Nodes]]
Name = 'Sepolia'
WSURL = 'wss://arbitrum-sepolia.infura.io/ws/v3/UPDATE_YOUR_API_KEY_Infura'
HTTPURL = 'https://arbitrum-sepolia.infura.io/v3/UPDATE_YOUR_API_KEY_Infura'



